# Generated by Django 5.0.1 on 2024-01-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False},
        ),
    ]
